export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  MANAGER= 'ROLE_MANAGER',
  CUSTOMER='ROLE_CUSTOMER',
  AGENT='ROLE_AGENT',
  LEVEL_1='ROLE_LEVEL_1',
  LEVEL_2='ROLE_LEVEL_2',
}
